check_softwareupdate.sh: change to /tmp before calling brew, otherwise the _nagios user may not be able to access its current work directory:
> shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
> job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
> Error: The current working directory doesn't exist, cannot proceed.

Signed-off-by: Christian Kujau <lists@nerdbynature.de>