Something in smartctl output has changed and check_smartctl would exit with:
 CRITICAL: device /dev/nvme0n1 of type nvme,0x1 does not pass temperature information

Also, hardcode to use python2 because it won't run with python3
just yet:

 TabError: inconsistent use of tabs and spaces in indentation

Signed-off-by: Christian Kujau <lists@nerdbynature.de>